name: Konnect Data Plane Bootstrap

on:
  workflow_dispatch:
    inputs:
      cp-name:
        description: "Control Plane (Runtime Group) name"
        required: true
        default: gm-sakaguchi-training
      region:
        description: "Konnect region (us, eu, ... )"
        required: true
        default: us
      ttl-seconds:
        description: "Auto remove container after seconds (0 to keep)"
        required: false
        default: "0"
      image-digest:
        description: "Optional sha256:<digest> (no quotes). If set, overrides tag and builds repo@digest image ref."
        required: false
        default: ""
  push:
    paths:
      - "scripts/konnect-dp-bootstrap.sh"
      - ".github/workflows/konnect-dp-ci.yml"

jobs:
  bootstrap-dp:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    env:
      KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (openssl,jq,docker already present)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Parse values-golden.yaml (image & labels)
        id: parse-values
        shell: bash
        run: |
          set -euo pipefail
          YQ_VERSION="v4.44.3"
          sudo wget -q https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          test -f values-golden.yaml || { echo 'values-golden.yaml not found' >&2; exit 1; }
          echo '--- values-golden.yaml (first 120 lines) ---'
          sed -n '1,120p' values-golden.yaml
          REPO=$(yq -r '.image.repository // ""' values-golden.yaml)
          TAG=$(yq -r '.image.tag // ""' values-golden.yaml)
          FILE_DIGEST=$(yq -r '.image.digest // ""' values-golden.yaml)
          # 優先順位: workflow_dispatch 入力 image-digest > 環境変数 IMAGE_DIGEST > ファイル内 digest
          INPUT_DIGEST='${{ github.event.inputs.image-digest }}'
          ENV_DIGEST="${IMAGE_DIGEST:-}"
          DIGEST="${INPUT_DIGEST:-${ENV_DIGEST:-$FILE_DIGEST}}"
          if [[ -z "$REPO" ]]; then echo 'image.repository not set' >&2; exit 1; fi
          if [[ -n "$DIGEST" ]]; then
            # プレーン 64hex の場合は sha256: を付与
            if [[ "$DIGEST" =~ ^[0-9a-fA-F]{64}$ ]]; then
              DIGEST="sha256:$DIGEST"
            fi
            if [[ ! "$DIGEST" =~ ^sha256:[0-9a-fA-F]{64}$ ]]; then
              echo "Provided digest format invalid: $DIGEST" >&2; exit 1
            fi
            IMAGE="${REPO}@${DIGEST}"
            echo "Digest mode: $DIGEST"
          else
            [[ -n "$TAG" ]] || TAG=latest
            IMAGE="${REPO}:${TAG}"
            echo "Tag mode: $TAG"
          fi
          LABELS=$(yq -r '.env.cluster_dp_labels // ""' values-golden.yaml)
          echo "Computed IMAGE=$IMAGE"
          echo "Computed LABELS=$LABELS"
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
          echo "labels=$LABELS" >> "$GITHUB_OUTPUT"

      - name: Login Docker Hub (optional)
        if: env.DOCKERHUB_USER && env.DOCKERHUB_TOKEN
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USER}" --password-stdin
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run bootstrap script
        run: |
          IMAGE_ARG="${{ steps.parse-values.outputs.image }}"
          LABELS_ARG="${{ steps.parse-values.outputs.labels }}"
          echo "Using only values-golden.yaml derived configuration"
          echo "Using IMAGE_ARG=$IMAGE_ARG"
          echo "Using LABELS_ARG=$LABELS_ARG"
          bash scripts/konnect-dp-bootstrap.sh \
            --cp-name "${{ github.event.inputs.cp-name || 'gm-sakaguchi-training' }}" \
            --region "${{ github.event.inputs.region || 'us' }}" \
            --image "$IMAGE_ARG" \
            --labels "$LABELS_ARG" \
            --container-name konnect-dp-ci \
            --ttl-seconds "${{ github.event.inputs.ttl-seconds || '0' }}" -v

      - name: Show running containers
        run: docker ps -a | grep konnect-dp-ci || true

      - name: Tail logs (post)
        run: docker logs --tail 200 konnect-dp-ci || true

      - name: Optional cleanup (if ttl=0 user may keep container)
        if: ${{ github.event.inputs.ttl-seconds == '0' }}
        run: echo "Skipping automatic container removal; ttl=0"
